
# -- Black -----------------------------------------------------------------------------

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = "__init__.py|__main__.py|_version.py"
force-exclude = """
/(
    anlz/structs.py |
    mysettings/structs.py
)\
"""
