name: Update AoC Badges
on:
  schedule:                                      # run workflow based on schedule
    - cron: '6 5 1-25 12 *'                      # from the 1. December till 25. December every day at 5:06am (avoid load at full hours)

  workflow_dispatch:


jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update 2023 Badges
        uses: joblo2213/aoc-badges-action@v3
        with:
          userid: 2300201
          session: ${{ secrets.AOC_SESSION }}
          year: 2023
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/⭐_2023-)[0-9]+(?=-yellow)'

      - name: Update 2022 Badges
        uses: joblo2213/aoc-badges-action@v3
        with:
          userid: 2300201
          session: ${{ secrets.AOC_SESSION }}
          year: 2022
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/⭐_2022-)[0-9]+(?=-yellow)'

      - name: Update 2021 Badges
        uses: joblo2213/aoc-badges-action@v3
        with:
          userid: 2300201
          session: ${{ secrets.AOC_SESSION }}
          year: 2021
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/⭐_2021-)[0-9]+(?=-yellow)'

      - uses: stefanzweifel/git-auto-commit-action@v4     # Step that pushes these local changes back to your github repo
        with:
          commit_message: Update badges
          file_pattern: README.md
